spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1013121533343-kmnpje65ggf584h5ubn1f8cumtat8492.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: ywXZK5b9O4PyMCIXM7EE
            client-secret: kXa1jbatMx
            client-name: Naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 8d61b63caf523bd7b046fdda905cf11f
            client-secret: TYjBlvOkPLQBoQbLzCQEgGYsujr0a1nk
            client-name: Kakao
            client-authentication-method: POST
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    spring.security: DEBUG #로깅 레벨 설정

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

springdoc:
  packages-to-scan : spring.security
  swagger-ui :
    path : /swagger-ui.html # html 문서 접속 경로
    tags-sorter : alpha # 태그 정렬 기준
    operations-sorter : alpha # alpha (알파벳 오름차순), method (HTTP 메소드 순)
    doc-expansion: none # tag, operation 펼치는 방식
  api-docs :
    path : /api-docs/json
    groups :
      enabled : true
  cache :
    disabled : true
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type : application/json;charset=UTF-8